// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Payroll.PayrollPFEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EmpJoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFAccountNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PFPolicyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PfActivationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("VoluntaryPercent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PFPolicyId");

                    b.ToTable("Payroll_PFEmployees", "dbo");
                });

            modelBuilder.Entity("Domain.Entities.Payroll.PayrollPFPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CalculationBase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContributionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EmployeeContributionPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EmployeeFixedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EmployerContributionPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EmployerFixedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MinWorkingDays")
                        .HasColumnType("int");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WageLimit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Payroll_PFPolicy", "dbo");
                });

            modelBuilder.Entity("Domain.Entities.Payroll.PayrollPFSettlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeePFId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SettlementDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalBalance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeePFId");

                    b.ToTable("Payroll_PFSettlement", "dbo");
                });

            modelBuilder.Entity("Domain.Entities.Payroll.PayrollPFTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("EmployeeContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeePFId")
                        .HasColumnType("int");

                    b.Property<decimal>("EmployerContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsManual")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TransactionMonth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeePFId");

                    b.ToTable("Payroll_PFTransaction", "dbo");
                });

            modelBuilder.Entity("Domain.Entities.Payroll.PayrollPFEmployee", b =>
                {
                    b.HasOne("Domain.Entities.Payroll.PayrollPFPolicy", "PFPolicy")
                        .WithMany("PFEmployee")
                        .HasForeignKey("PFPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PFPolicy");
                });

            modelBuilder.Entity("Domain.Entities.Payroll.PayrollPFSettlement", b =>
                {
                    b.HasOne("Domain.Entities.Payroll.PayrollPFEmployee", "EmployeePF")
                        .WithMany("PfSettlements")
                        .HasForeignKey("EmployeePFId");

                    b.Navigation("EmployeePF");
                });

            modelBuilder.Entity("Domain.Entities.Payroll.PayrollPFTransaction", b =>
                {
                    b.HasOne("Domain.Entities.Payroll.PayrollPFEmployee", "EmployeePF")
                        .WithMany("PFTransactions")
                        .HasForeignKey("EmployeePFId");

                    b.Navigation("EmployeePF");
                });

            modelBuilder.Entity("Domain.Entities.Payroll.PayrollPFEmployee", b =>
                {
                    b.Navigation("PFTransactions");

                    b.Navigation("PfSettlements");
                });

            modelBuilder.Entity("Domain.Entities.Payroll.PayrollPFPolicy", b =>
                {
                    b.Navigation("PFEmployee");
                });
#pragma warning restore 612, 618
        }
    }
}
